USE mi_amazon;

-- Insertar productos con stock aleatorio
INSERT INTO productos (nombre, descripcion, precio, imagen, stock) VALUES 
('Testosterone Booster', 'Testosterone Booster de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aumenta la producción natural de testosterona.', 1260.04, 'images/special_1.jpg', 25),
('MK-677', 'MK-677 SARM de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Estimula la hormona del crecimiento.', 373.32, 'images/special_2.jpg', 18),
('Testo-Max', 'Testo-Max booster natural de testosterona de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento.', 1221.28, 'images/special_3.jpg', 12),
('MK-2866', 'MK-2866 (Ostarine) SARM de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para ganar masa muscular magra.', 465.29, 'images/special_4.jpg', 30),
('Testo Surge', 'Testo Surge booster de testosterona de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento.', 662.15, 'images/special_5.jpg', 22),
('MK-677 Pro', 'MK-677 Pro versión avanzada para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula concentrada.', 398.48, 'images/special_6.jpg', 15),
('Testo Pump', 'Testo Pump pre-entreno con booster de testosterona de alta calidad para mejorar tu rendimiento y resultados.', 903.72, 'images/special_7.jpg', 20),
('MK-2866 Xtreme', 'MK-2866 Xtreme versión potenciada de Ostarine para mejorar tu rendimiento y resultados en el entrenamiento.', 574.09, 'images/special_8.jpg', 8),
('Testo Blast', 'Testo Blast booster extremo de testosterona de alta calidad para mejorar tu rendimiento y resultados.', 1289.45, 'images/special_9.jpg', 10),
('MK-677 Ultra', 'MK-677 Ultra fórmula premium para mejorar tu rendimiento y resultados en el entrenamiento. Máxima potencia.', 599.42, 'images/special_10.jpg', 14),

('Creatina Monohidrato 500g', 'Creatina Monohidrato pura 500g de alta calidad para aumentar fuerza, potencia y volumen muscular durante el entrenamiento.', 1543.26, 'images/product_11.jpg', 45),
('Whey Protein Banana', 'Whey Protein sabor Banana de alta calidad, 25g de proteína por porción para recuperación muscular post-entreno.', 534.99, 'images/product_12.jpg', 35),
('Shaker Verde 700ml', 'Shaker Verde de 700ml libre de BPA, con rejilla mezcladora para preparar tus batidos perfectos.', 808.35, 'images/product_13.jpg', 50),
('Pre-Entreno Nitro', 'Pre-Entreno Nitro con citrulina, beta-alanina y cafeína para máxima energía y pump muscular.', 813.62, 'images/product_14.jpg', 28),
('Glutamina 2000g', 'Glutamina L-Glutamina pura 2000g para recuperación muscular, sistema inmune y síntesis proteica.', 1456.39, 'images/product_15.jpg', 32),
('Creatina Monohidrato 2000g', 'Creatina Monohidrato 2000g presentación familiar, la más estudiada para fuerza y volumen muscular.', 750.04, 'images/product_16.jpg', 25),
('EAA 2000g', 'Aminoácidos Esenciales EAA 2000g, los 9 aminoácidos que tu cuerpo no puede producir naturalmente.', 1111.46, 'images/product_17.jpg', 20),
('Energy Blast Ultra', 'Energy Blast Ultra pre-entreno con fórmula avanzada de estimulantes y nootrópicos para máximo rendimiento.', 1095.31, 'images/product_18.jpg', 18),
('Casein Banana', 'Proteína Caseína sabor Banana de absorción lenta, ideal para tomar antes de dormir y mantener anabolismo.', 653.14, 'images/product_19.jpg', 22),
('Vegan Protein Banana', 'Proteína Vegana sabor Banana a base de guisante y arroz, libre de lactosa y gluten, 24g proteína.', 1244.4, 'images/product_20.jpg', 16);

-- Continuar con más productos (reduciendo para brevedad)...
-- Los demás productos mantienen el mismo formato pero con descripciones mejoradas y stock asignado

('Pre-Entreno Force', 'Pre-Entreno Force de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con ingredientes avanzados para máxima energía.', 1281.97, 'images/product_21.jpg', 18),
('Creatina Kre-Alkalyn 500g', 'Creatina Kre-Alkalyn 500g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula bufferizada para mejor absorción.', 1115.88, 'images/product_22.jpg', 25),
('Vegan Protein Fresa', 'Vegan Protein Fresa de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Proteína vegetal con aminoácidos esenciales.', 758.37, 'images/product_23.jpg', 20),
('Creatina HCL 1000g', 'Creatina HCL 1000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soluble y de rápida absorción.', 872.27, 'images/product_24.jpg', 15),
('Energy Blast Ultra', 'Energy Blast Ultra de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con extractos naturales y cafeína.', 216.24, 'images/product_25.jpg', 10),
('Whey Protein Chocolate', 'Whey Protein Chocolate de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. 25g de proteína por porción.', 230.01, 'images/product_26.jpg', 35),
('Creatina HCL 2000g', 'Creatina HCL 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para entrenamientos intensos.', 529.55, 'images/product_27.jpg', 12),
('Isolate Protein Vainilla', 'Isolate Protein Vainilla de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. 27g de proteína aislada por porción.', 1223.49, 'images/product_28.jpg', 8),
('Energy Blast Ultra', 'Energy Blast Ultra de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con L-carnitina y cafeína para mayor energía.', 194.14, 'images/product_29.jpg', 14),
('Pre-Entreno Xplode', 'Pre-Entreno Xplode de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula explosiva para máxima energía.', 439.96, 'images/product_30.jpg', 20),
('Creatina Monohidrato 300g', 'Creatina Monohidrato 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aumenta la fuerza y el rendimiento.', 1416.44, 'images/product_31.jpg', 25),
('Creatina Kre-Alkalyn 300g', 'Creatina Kre-Alkalyn 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Absorción rápida y efectiva.', 424.15, 'images/product_32.jpg', 18),
('Shaker Azul 700ml', 'Shaker Azul de 700ml con diseño ergonómico y rejilla mezcladora para preparar tus batidos de forma cómoda.', 816.34, 'images/product_33.jpg', 50),
('Vegan Protein Chocolate', 'Vegan Protein Chocolate de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Sin ingredientes de origen animal.', 643.45, 'images/product_34.jpg', 16),
('Cinturón de levantamiento 2000', 'Cinturón de levantamiento 2000 de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soporte lumbar y abdominal.', 970.7, 'images/product_35.jpg', 12),
('Pre-Entreno Max', 'Pre-Entreno Max de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con beta-alanina y cafeína para mayor energía.', 864.45, 'images/product_36.jpg', 22),
('Weight Lifting Gloves 500', 'Weight Lifting Gloves 500 de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Agarre superior y comodidad.', 875.67, 'images/product_37.jpg', 30),
('BCAA 2:1:1 1000g', 'BCAA 2:1:1 1000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aminoácidos de cadena ramificada para recuperación muscular.', 1111.12, 'images/product_38.jpg', 25),
('Creatina Kre-Alkalyn 300g', 'Creatina Kre-Alkalyn 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula avanzada para máxima efectividad.', 1204.28, 'images/product_39.jpg', 10),
('Muñequeras Neopreno', 'Muñequeras Neopreno de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soporte y compresión para muñecas.', 1641.18, 'images/product_40.jpg', 18),
('BCAA 2:1:1 2000g', 'BCAA 2:1:1 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para entrenamientos de resistencia.', 109.82, 'images/product_41.jpg', 35),
('Vegan Protein Chocolate', 'Vegan Protein Chocolate de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Sabor delicioso y 24g de proteína.', 1100.41, 'images/product_42.jpg', 20),
('Creatina Monohidrato 300g', 'Creatina Monohidrato 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aumenta la fuerza y el volumen muscular.', 125.46, 'images/product_43.jpg', 50),
('BCAA 2:1:1 500g', 'BCAA 2:1:1 500g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aminoácidos esenciales para la recuperación.', 1020.0, 'images/product_44.jpg', 15),
('Casein Vainilla', 'Casein Vainilla de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Proteína de absorción lenta para la noche.', 274.38, 'images/product_45.jpg', 12),
('Creatina HCL 300g', 'Creatina HCL 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soluble en agua, sin sabor.', 246.67, 'images/product_46.jpg', 18),
('Isolate Protein Chocolate', 'Isolate Protein Chocolate de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. 27g de proteína aislada por porción.', 1472.54, 'images/product_47.jpg', 10),
('Nitro Pump Nitro', 'Nitro Pump Nitro de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con óxido nítrico para mayor bombeo.', 277.27, 'images/product_48.jpg', 14),
('Creatina Kre-Alkalyn 1000g', 'Creatina Kre-Alkalyn 1000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Máxima concentración y pureza.', 1516.74, 'images/product_49.jpg', 8),
('Knee Sleeves 300', 'Knee Sleeves 300 de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soporte y compresión para las rodillas.', 1687.42, 'images/product_50.jpg', 20),
('Glutamina 500g', 'Glutamina 500g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ayuda a la recuperación y reducción del dolor muscular.', 1100.07, 'images/product_51.jpg', 25),
('Knee Sleeves 1000', 'Knee Sleeves 1000 de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Mayor soporte y estabilidad para tus rodillas.', 830.79, 'images/product_52.jpg', 18),
('Shaker Negro 700ml', 'Shaker Negro 700ml de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Diseño elegante y funcional.', 922.25, 'images/product_53.jpg', 30),
('BCAA 2:1:1 1000g', 'BCAA 2:1:1 1000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aminoácidos esenciales para la recuperación muscular.', 992.8, 'images/product_54.jpg', 25),
('Pre-Entreno Nitro', 'Pre-Entreno Nitro de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con ingredientes energizantes y potenciadores del rendimiento.', 1558.56, 'images/product_55.jpg', 12),
('Shaker Morado 700ml', 'Shaker Morado 700ml de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Mezcla perfecta y sin grumos.', 901.51, 'images/product_56.jpg', 50),
('Creatina HCL 1000g', 'Creatina HCL 1000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Rápida absorción y sin retención de líquidos.', 105.57, 'images/product_57.jpg', 18),
('Shaker Verde 700ml', 'Shaker Verde 700ml de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para tus batidos de proteínas.', 1017.62, 'images/product_58.jpg', 25),
('Creatina Kre-Alkalyn 2000g', 'Creatina Kre-Alkalyn 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula avanzada para máxima efectividad.', 1027.31, 'images/product_59.jpg', 10),
('Isolate Protein Vainilla', 'Isolate Protein Vainilla de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. 27g de proteína aislada por porción.', 1672.29, 'images/product_60.jpg', 8),
('Shaker Morado 700ml', 'Shaker Morado 700ml de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con diseño ergonómico y tapa a prueba de fugas.', 1249.67, 'images/product_61.jpg', 50),
('Creatina HCL 300g', 'Creatina HCL 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Sin sabor y fácil de mezclar.', 654.84, 'images/product_62.jpg', 20),
('Glutamina 300g', 'Glutamina 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Favorece la recuperación y el crecimiento muscular.', 831.64, 'images/product_63.jpg', 25),
('Vegan Protein Fresa', 'Vegan Protein Fresa de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Proteína vegetal con sabor natural.', 622.2, 'images/product_64.jpg', 18),
('Knee Sleeves 2000', 'Knee Sleeves 2000 de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soporte máximo para tus rodillas durante el entrenamiento.', 1444.83, 'images/product_65.jpg', 12),
('Creatina HCL 2000g', 'Creatina HCL 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para aumentar la fuerza y el rendimiento.', 164.56, 'images/product_66.jpg', 15),
('Pre-Entreno Max', 'Pre-Entreno Max de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con ingredientes de última generación para máxima energía.', 1149.88, 'images/product_67.jpg', 22),
('Energy Blast Ultra', 'Energy Blast Ultra de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con extractos naturales y cafeína para mayor energía.', 791.01, 'images/product_68.jpg', 18),
('Cinturón de levantamiento 1000', 'Cinturón de levantamiento 1000 de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soporte lumbar y abdominal.', 662.49, 'images/product_69.jpg', 12),
('EAA 300g', 'EAA 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aminoácidos esenciales para la recuperación y el crecimiento muscular.', 1540.2, 'images/product_70.jpg', 10),
('BCAA 2:1:1 2000g', 'BCAA 2:1:1 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para entrenamientos de resistencia y recuperación.', 301.24, 'images/product_71.jpg', 35),
('Whey Protein Cookies & Cream', 'Whey Protein Cookies & Cream de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. 25g de proteína por porción y sabor irresistible.', 176.29, 'images/product_72.jpg', 20),
('Vegan Protein Fresa', 'Vegan Protein Fresa de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Proteína vegetal con aminoácidos esenciales.', 1518.78, 'images/product_73.jpg', 15),
('Isolate Protein Chocolate', 'Isolate Protein Chocolate de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. 27g de proteína aislada por porción.', 1409.13, 'images/product_74.jpg', 10),
('Casein Cookies & Cream', 'Casein Cookies & Cream de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Proteína de absorción lenta con sabor delicioso.', 446.42, 'images/product_75.jpg', 18),
('Vegan Protein Fresa', 'Vegan Protein Fresa de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Sabor natural y 24g de proteína por porción.', 797.3, 'images/product_76.jpg', 25),
('Creatina Kre-Alkalyn 2000g', 'Creatina Kre-Alkalyn 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula avanzada para máxima efectividad.', 1008.1, 'images/product_77.jpg', 12),
('Shaker Verde 700ml', 'Shaker Verde 700ml de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para tus batidos de proteínas y suplementos.', 230.18, 'images/product_78.jpg', 50),
('Shaker Rojo 700ml', 'Shaker Rojo 700ml de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Diseño atractivo y funcional.', 1303.73, 'images/product_79.jpg', 30),
('Creatina Monohidrato 500g', 'Creatina Monohidrato 500g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aumenta la fuerza y el volumen muscular.', 566.78, 'images/product_80.jpg', 25),
('Knee Sleeves 300', 'Knee Sleeves 300 de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soporte y compresión para las rodillas.', 983.79, 'images/product_81.jpg', 20),
('Creatina HCL 2000g', 'Creatina HCL 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para entrenamientos intensos y definición muscular.', 1694.56, 'images/product_82.jpg', 10),
('Isolate Protein Cookies & Cream', 'Isolate Protein Cookies & Cream de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. 27g de proteína aislada por porción y sabor delicioso.', 1136.11, 'images/product_83.jpg', 15),
('Vegan Protein Vainilla', 'Vegan Protein Vainilla de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Proteína vegetal con aminoácidos esenciales.', 1097.35, 'images/product_84.jpg', 20),
('Creatina Monohidrato 500g', 'Creatina Monohidrato 500g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aumenta la fuerza y el volumen muscular.', 210.46, 'images/product_85.jpg', 50),
('Knee Sleeves 300', 'Knee Sleeves 300 de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Soporte y compresión para las rodillas.', 798.15, 'images/product_86.jpg', 25),
('Creatina Monohidrato 2000g', 'Creatina Monohidrato 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. La creatina más pura y efectiva del mercado.', 652.8, 'images/product_87.jpg', 12),
('Creatina HCL 300g', 'Creatina HCL 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Sin sabor y fácil de mezclar en tus bebidas.', 437.07, 'images/product_88.jpg', 18),
('Creatina Kre-Alkalyn 300g', 'Creatina Kre-Alkalyn 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula avanzada para máxima efectividad.', 1389.58, 'images/product_89.jpg', 10),
('Shaker Rojo 700ml', 'Shaker Rojo 700ml de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con diseño ergonómico y tapa a prueba de fugas.', 1234.71, 'images/product_90.jpg', 50),
('Creatina Kre-Alkalyn 2000g', 'Creatina Kre-Alkalyn 2000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula avanzada para máxima efectividad.', 797.98, 'images/product_91.jpg', 12),
('Energy Blast Force', 'Energy Blast Force de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con ingredientes energizantes y potenciadores del rendimiento.', 308.72, 'images/product_92.jpg', 18),
('Isolate Protein Banana', 'Isolate Protein Banana de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. 27g de proteína aislada por porción y sabor delicioso.', 143.99, 'images/product_93.jpg', 25),
('Creatina HCL 300g', 'Creatina HCL 300g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Ideal para aumentar la fuerza y el rendimiento.', 605.71, 'images/product_94.jpg', 20),
('Energy Blast Max', 'Energy Blast Max de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con extractos naturales y cafeína para mayor energía.', 849.49, 'images/product_95.jpg', 18),
('Nitro Pump Ultra', 'Nitro Pump Ultra de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Con óxido nítrico para mayor bombeo y energía.', 1016.43, 'images/product_96.jpg', 10),
('Vegan Protein Chocolate', 'Vegan Protein Chocolate de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Sabor delicioso y 24g de proteína por porción.', 421.09, 'images/product_97.jpg', 25),
('Shaker Verde 500ml', 'Shaker Verde 500ml de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Diseño compacto y fácil de transportar.', 522.07, 'images/product_98.jpg', 30),
('Creatina Monohidrato 1000g', 'Creatina Monohidrato 1000g de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Aumenta la fuerza y el volumen muscular.', 537.88, 'images/product_99.jpg', 25),
('Pre-Entreno Xplode', 'Pre-Entreno Xplode de alta calidad para mejorar tu rendimiento y resultados en el entrenamiento. Fórmula explosiva para máxima energía y enfoque.', 1113.33, 'images/product_100.jpg', 18);